name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")" >> $GITHUB_ENV
      - name: build shadowJar
        run: |
          ./gradlew shadowJar
      - name: set env
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")" >> $GITHUB_ENV
      - name: Compress
        run: |
          mkdir presto-query-extractor-${{ env.VERSION }}
          mv presto-query-extractor/build/libs/presto-query-extractor-all.jar presto-query-extractor-${{ env.VERSION }}
          zip -r presto-query-extractor-${{ env.VERSION }}.zip presto-query-extractor-${{ env.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            presto-query-extractor-${{ env.VERSION }}.zip
